import { useCallback } from 'react';
import { Message } from '../types';
import styles from './ExportButton.module.css';

interface Props {
  messages: Message[];
  disabled?: boolean;
}

export function ExportButton({ messages, disabled }: Props) {

  const exportPDF = useCallback(() => {
    // Filter only meaningful messages (not tool calls)
    const relevant = messages.filter(m => m.role !== 'tool' && m.text.trim().length > 0);
    if (relevant.length === 0) return;

    // Build HTML content for the PDF
    const now     = new Date().toLocaleString();
    const topic   = relevant[0]?.text?.slice(0, 60) ?? 'Research Session';

    const rows = relevant.map(m => {
      const label = m.role === 'user' ? '🎤 You' : '🤖 ResearchAI';
      const cls   = m.role === 'user' ? 'user' : 'agent';
      return `
        <div class="msg ${cls}">
          <div class="label">${label}</div>
          <div class="text">${m.text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</div>
          <div class="time">${new Date(m.timestamp).toLocaleTimeString()}</div>
        </div>
      `;
    }).join('');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>ResearchAI Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #1a1a2e; padding: 40px; }
    .header { border-bottom: 3px solid #6c63ff; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { font-size: 28px; color: #6c63ff; }
    .header p  { color: #666; margin-top: 6px; font-size: 14px; }
    .msg { margin-bottom: 20px; padding: 16px; border-radius: 10px; page-break-inside: avoid; }
    .msg.user  { background: #f0f0ff; border-left: 4px solid #6c63ff; }
    .msg.agent { background: #f8f9fa; border-left: 4px solid #28a745; }
    .label { font-weight: 700; font-size: 13px; margin-bottom: 6px; color: #555; }
    .text  { font-size: 15px; line-height: 1.7; color: #1a1a2e; }
    .time  { font-size: 11px; color: #999; margin-top: 8px; }
    .footer { margin-top: 40px; border-top: 1px solid #eee; padding-top: 16px; font-size: 12px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎙️ ResearchAI — Research Report</h1>
    <p>Topic: ${topic}</p>
    <p>Generated: ${now}</p>
  </div>
  ${rows}
  <div class="footer">Generated by ResearchAI · Powered by Gemini Live API · Google ADK</div>
</body>
</html>`;

    // Open in new tab and trigger print-to-PDF
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.onload = () => {
      win.focus();
      win.print(); // browser print dialog → "Save as PDF"
    };
  }, [messages]);

  return (
    <button
      className={styles.btn}
      onClick={exportPDF}
      disabled={disabled || messages.filter(m => m.role !== 'tool').length === 0}
      title="Export research as PDF"
    >
      📄 Export PDF
    </button>
  );
}